compat with opm

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -94,10 +94,22 @@ jobs:
               exit 1
           }
 
+      - name: Rename release folder
+        shell: pwsh
+        run: |
+          $releaseDir = "build/release"
+          $newDir = "AutoSceneSwitcher"
+          if (Test-Path $releaseDir) {
+              Rename-Item -Path $releaseDir -NewName $newDir
+          } else {
+              Write-Error "Release folder not found!"
+              exit 1
+          }
+          
       - name: Zip binaries folder
         run: |
           $zipFile = "build/AutoSceneSwitcher_msvc_64.zip"
-          $folder = "build/release"
+          $folder = "build/AutoSceneSwitcher"
           Compress-Archive -Path $folder -DestinationPath $zipFile
         shell: pwsh
           
